name: Release

env:
  OUTPUT_DIRECTORY: ${{ github.workspace }}/output

on:
  release:
    branches:
      - master
    tags:
      - '*'
    types:
      - published

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c Release
      - name: Test
        run: dotnet test --no-build --verbosity normal -c Release
      - name: Get version
        id: version
        uses: battila7/get-version-action@v2
      - name: Pack
        run: dotnet pack --no-restore --no-build -c Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.OUTPUT_DIRECTORY }}
      - name: Push
        run: dotnet nuget push ${{ env.OUTPUT_DIRECTORY }}/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}